# Generated by Django 5.1.5 on 2025-08-05 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('night_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('night_shift_factor_applied', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('salary_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lunch_deduction_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_deductions_description', models.CharField(blank=True, max_length=255, null=True)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('sync', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pay_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payrolls.payperiod')),
            ],
        ),
    ]
