# Generated by Django 5.1.5 on 2025-05-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrolls', '0002_payperiod_salaryrecord_pay_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='night_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='night_shift_factor_applied',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='regular_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
