# Generated by Django 5.1.5 on 2025-05-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrolls', '0003_salaryrecord_night_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='lunch_deduction_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='other_deductions_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
