# Generated by Django 5.1.5 on 2025-05-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='biweekly_hours',
            field=models.DecimalField(decimal_places=2, default=96.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='night_shift_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
