# Generated by Django 5.1.5 on 2025-05-12 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='face_tamplate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='fingerprint_hash',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='use_face_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='use_finger_print',
        ),
    ]
