# Generated by Django 5.1.5 on 2025-05-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0002_timer_expected_hours_timer_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='expected_hours',
        ),
        migrations.AddField(
            model_name='timer',
            name='is_night_shift',
            field=models.BooleanField(default=False),
        ),
    ]
