# Generated by Django 5.1.5 on 2025-08-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('night_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('extra_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lunch_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_in', models.DateTimeField()),
                ('timestamp_out', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('nfc', 'NFC Token')], max_length=80)),
                ('paid', models.BooleanField(default=False)),
                ('nfc_token', models.TextField(blank=True, null=True)),
                ('sync', models.BooleanField(default=False)),
            ],
        ),
    ]
