# Generated by Django 5.1.5 on 2025-02-02 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_in', models.DateTimeField(auto_now_add=True)),
                ('timestamp_out', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('fingerprint', 'Huella'), ('faceId', 'Reconocimiento Facial')], max_length=80)),
                ('hash', models.TextField()),
                ('sync', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
