# Generated by Django 5.1.5 on 2025-02-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceregister',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='pay_period',
            field=models.DateField(null=True),
        ),
    ]
