# Generated by Django 5.1.5 on 2025-08-05 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('payrolls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedetail',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancedetail',
            name='pay_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.payperiod'),
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='pay_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payrolls.payperiod'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancedetail',
            unique_together={('employee', 'work_date')},
        ),
    ]
