# Generated by Django 5.1.5 on 2025-05-06 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendanceregister_timestamp_in'),
        ('payrolls', '0003_salaryrecord_night_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceregister',
            name='pay_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payrolls.payperiod'),
        ),
    ]
