# Generated by Django 5.1.5 on 2025-05-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendanceregister_pay_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceregister',
            name='unique_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceregister',
            name='method',
            field=models.CharField(choices=[('fingerprint', 'Huella'), ('faceId', 'Reconocimiento Facial'), ('pin', 'PIN')], max_length=80),
        ),
    ]
