# Generated by Django 5.1.5 on 2025-05-07 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendanceregister_unique_pin_and_more'),
        ('payrolls', '0003_salaryrecord_night_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('night_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('extra_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lunch_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.payperiod')),
            ],
            options={
                'unique_together': {('employee', 'work_date')},
            },
        ),
    ]
