# Generated by Django 5.1.5 on 2025-05-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceregister',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceregister',
            name='method',
            field=models.CharField(choices=[('fingerprint', 'Huella'), ('faceId', 'Reconocimiento Facial'), ('pin', 'PIN'), ('qr_code', 'QR Code')], max_length=80),
        ),
    ]
