# Generated by Django 5.1.5 on 2025-05-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendanceregister_qr_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendanceregister',
            old_name='qr_code',
            new_name='nfc_token',
        ),
        migrations.RemoveField(
            model_name='attendanceregister',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='attendanceregister',
            name='unique_pin',
        ),
        migrations.AlterField(
            model_name='attendanceregister',
            name='method',
            field=models.CharField(choices=[('nfc', 'NFC Token')], max_length=80),
        ),
    ]
